# Generated by Django 4.0.5 on 2022-06-28 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls_and_questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollconfig',
            name='enabled',
            field=models.BooleanField(default=True, verbose_name='is enabled'),
        ),
    ]
